spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://0.0.0.0:3306/smart-pot}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

invalidate:
  cache:
    delay: ${INVALIDATE_CACHE_DELAY:60000}

mqtt:
  host: ${MQTT_HOST:broker.shiftr.io}
  port: ${MQTT_PORT:1883}
  username: ${MQTT_USER:79b5b7ac}
  password: ${MQTT_PASSWORD:7614b0c8da666f35}
  automaticReconnect: ${MQTT_AUTO_RECONNECT:true}
  cleanSession: ${MQTT_CLEAN_SESSION:true}
  connectionTimeout: ${MQTT_CONN_TIMEOUT:10}

device:
  status:
    collect:
      delay: ${DEVICE_STATUS_COLLECT_DELAY:60000}
    clear:
      cache:
        delay: ${DEVICE_STATUS_CLEAR_CACHE_DELAY:600000}

