spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3306/smart-pot
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


invalidate:
  cache:
    delay: 60000
#    delay: 86400000

mqtt:
  host: broker.shiftr.io
  port: 1883
  username: 79b5b7ac
  password: 7614b0c8da666f35
  automaticReconnect: true
  cleanSession: true
  connectionTimeout: 10

device:
  status:
    collect:
      delay: 60000
    clear:
      cache:
        delay: 600000

